name: dependency-scan

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  dep_scan:
    name: Run Dependency Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependency Check
        run: |
          sudo apt-get update
          sudo apt-get install -y owasp-dependency-check

      - name: Run OWASP Dependency Check
        run: |
          dependency-check.sh --project juice-shop --scan /github/workspace --out /github/workspace/reports --format JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
