name: Dependency Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build:frontend

    - name: Install CycloneDX and OWASP Dep-Scan
      run: |
        sudo npm install -g @cyclonedx/cdxgen
        pip install owasp-depscan

    - name: Generate CycloneDX BOM
      run: |
        cdxgen -o $GITHUB_WORKSPACE/cyclonedx-bom.json

    - name: Run OWASP Dep-Scan Detailed Report
      run: |
        owasp-depscan -i $GITHUB_WORKSPACE/cyclonedx-bom.json -o $GITHUB_WORKSPACE/reports --detail
      continue-on-error: true

    - name: Run OWASP Dep-Scan Summary Report
      run: |
        owasp-depscan -i $GITHUB_WORKSPACE/cyclonedx-bom.json -o $GITHUB_WORKSPACE/reports --summary
      continue-on-error: true

    - name: Upload reports
      uses: actions/upload-artifact@v3
      with:
        name: depscan-reports
        path: $GITHUB_WORKSPACE/reports

    - name: Cleanup
      run: |
        echo "Cleaning up..."
