name: Bot scan
on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]
  issues:
    types: [opened, edited, milestoned] 
permissions:
  issues: write
  pull-requests: write

jobs:
  Snyk_scanning:
    name: Snyk Bot scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Snyk Bot scan
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          echo "Downloading and authenticating Snyk CLI..."
          curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.1100.0/snyk-linux"
          chmod +x snyk
          ./snyk auth ${{ secrets.SNYK_TOKEN }}
          echo "Running Snyk test and monitor..."
          ./snyk test --all-projects --color || true
          ./snyk monitor --all-projects || true
  TruffleHog_scanning:
    name: TruffleHog Bot scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: TruffleHog Bot scan
        uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
        with:
            args: ${{ github.event.repository.default_branch }} HEAD --fail-verified
  BotCheck:
    name: Bot scan 
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [Snyk_scanning, TruffleHog_scanning]
    steps:
      - uses: itsarraj/pr-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



