name: Semgrep Scan

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  semgrep:
    permissions: write-all
    name: Run Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            semgrep --config semgrep.yml --output semgrep-results.json || true
            semgrep --config semgrep.yml .
          elif [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            semgrep --config "auto" --json --output semgrep-output.json
          fi

      - name: Read Semgrep output (for PR event)
        if: ${{ github.event_name == 'pull_request_target' }}
        id: semgrep-output
        run: |
          cat semgrep-output.json
          echo "semgrep-results=$(cat semgrep-output.json)" >> $GITHUB_ENV

      - name: Post or Update PR Comment
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Semgrep Scan Results**:
            ```
            ${{ steps.semgrep-output.outputs.semgrep-results }}
            ```
          edit-mode: replace
          reactions: rocket

