name: TruffleHog Scan

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  trufflehog_scan:
    name: TruffleHog Bot Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install TruffleHog
        run: |
          pip install truffleHog
          
      - name: Run TruffleHog Scan
        run: |
          trufflehog git https://github.com/trufflesecurity/test_keys --only-verified

