name: TruffleHog Scan

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  trufflehog_scan:
    name: TruffleHog Bot Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install TruffleHog
        run: |
          pip install truffleHog

      - name: Run TruffleHog Scan
        id: trufflehog
        continue-on-error: true
        run: |
          trufflehog --regex https://github.com/${{ github.repository }} --json > trufflehog-results.json 2> trufflehog-errors.log || true
          cat trufflehog-errors.log

      - name: Validate TruffleHog Results
        run: |
          if [ -s trufflehog-results.json ]; then
            # Perform any additional validation or conversion here
            echo "Results file created successfully."
          else
            echo "No results found." > trufflehog-formatted-results.json
          fi

      - name: Post TruffleHog Results as a PR Comment
        if: github.event.pull_request
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: trufflehog-results
          path: trufflehog-formatted-results.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload findings to GitHub Security (SARIF)
        if: github.event.pull_request
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trufflehog-results.json
