name: TruffleHog Scan

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  trufflehog_scan:
    name: TruffleHog Bot Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install TruffleHog
        run: |
          pip install truffleHog

      - name: Run TruffleHog Scan
        id: trufflehog
        continue-on-error: true
        run: |
          trufflehog --regex https://github.com/${{ github.repository }} > trufflehog-results.txt 2> trufflehog-errors.log || true
          echo 'trufflehog results'
          cat trufflehog-results.txt
          echo 'trufflehog errors'
          cat trufflehog-errors.log

      - name: Validate TruffleHog Results
        run: |
          if [ -s trufflehog-results.txt ]; then
            echo "Results file created successfully."
          else
            echo "No results found." > trufflehog-results.txt
          fi

      - name: Upload TruffleHog Results
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-results
          path: trufflehog-results.txt

      - name: Upload TruffleHog Errors
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-errors
          path: trufflehog-errors.log
