name: ZAP DAST Scan

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  zap_scan:
    name: Run ZAP DAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ZAP Baseline Scan with Console Output
        uses: zaproxy/action-baseline@v0.12.0
        continue-on-error: true
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://altoro.testfire.net'  
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          format: 'console'  # Ensure output is in the console

